INSERT INTO public.svc_proveedor(
            pro_id, pro_cuit, pro_razon_social, client_id, version, created_time, 
            created_user, updated_time, updated_user, deleted_time, nro_cta_cte)
    VALUES (nextval('svc_proveedor_pro_id_seq'), '30678186445', 'TELECOM PERSONAL S.A.', 1, 1, current_date, 
            0, current_date, 0, null, nextval('seq_cta_cte_id'));

INSERT INTO svc_servicio(
			id, codigo, descripcion, client_id, version, created_time, created_user, 
            updated_time, updated_user, deleted_time, servicio_tipo_id, proveedor_id)
    VALUES (nextval('svc_servicio_id_seq'), 'PERSONAL', 'Personal - Telefonía Celular', 1, 1, current_date, 0, 
            current_date, 0, null, 'VARIABLES', (SELECT pro_id FROM svc_proveedor WHERE pro_cuit='30678186445' AND client_id=1));


INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1169565987', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='00017' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1130648562', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='00140' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1164820811', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='00367' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1168846411', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='00369' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1168847947', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='00518' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1140546902', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='00518' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1130480293', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='00971' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1168562806', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='00971' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1168847605', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='01731' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1160991912', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='01810' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1152206589', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='01810' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1157599262', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='01810' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1158124306', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='01810' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1164556541', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='01860' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1130479107', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='02285' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1164733868', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='02645' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1169628246', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='03593' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1158436346', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='03593' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1162555609', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='03593' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1168752860', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='03648' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1161038721', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='03648' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1164556579', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='03648' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1164736409', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='04010' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1164886297', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='04148' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1162634728', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='04232' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1131064728', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='04232' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1130401645', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='04758' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1168539703', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='05469' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1168729312', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='05711' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1131352412', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='06732' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1165695508', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='06732' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1162817037', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='07147' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1162751094', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='07543' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1130973795', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='07917' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1124562305', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='07917' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1124562304', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='07917' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1165651938', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='09702' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1168689850', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='10793' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1133776536', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='10793' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
INSERT INTO public.usr_afiliado_suscripcion(id, numero_suscripcion, servicio_id, afiliado_id, client_id, version, created_time, created_user, updated_time, updated_user, deleted_time, activo) VALUES (nextval('usr_afiliado_suscripcion_id_seq'), '1169911961', (SELECT id FROM public.svc_servicio WHERE codigo='PERSONAL' AND client_id=1 AND deleted_time is null), (SELECT id FROM public.usr_afiliado WHERE id_externo='07593' AND client_id=1 AND deleted_time is null), 1, 1, current_date, 0, current_date, 0, null, true);
